### ISSUE TITLE
改进 屏幕与显示

### ISSUE THREAD

**Issue by duzhaokun123** [qinlili23333/PureAndroid#5]
这类没有，加上

## 屏幕与显示

0.  兼容刘海屏，全面屏等各种怪异屏幕
1.  支持横屏
2.  在平板电脑等大尺寸屏幕设备上显示内容不变形，模糊，错位等导致不美观甚至影响使用
3.  `*`兼容自由式多窗口模式
4.  视频类应用支持 `wifi display`
5.  视频类应用支持画中画模式

暂且这些想到再加

**Comment by duzhaokun123** [comment]
6.  使应用界面与导航栏，通知栏衔接自然

**Comment by qinlili23333** [comment]
已作出对应修改

**Comment by duzhaokun123** [comment]
这么你的公约官方 app 就没有遵守公约了，不支持横屏，有在改吗

另外 0xa的0 与 0x7的0 重复了

**Comment by duzhaokun123** [comment]
修改一个错误
 
0xa的4 不是`wifi display`而是`Miracast`

**Comment by qinlili23333** [comment]
官方app在修改了
